### ISSUE TITLE
图片有概率发不出来

### ISSUE THREAD

**Issue by xmbhjQAQ** [Rinkuto/koishi-plugin-pixiv#3]
session Error: Error with request send_group_msg, args: {"group_id":"912036281","message":[{"type":"at","data":{"qq":"2719989194"}},{"type":"image","data":{"file":"https://i.pixiv.re/img-original/img/2018/01/01/00/15/32/66569463_p1.png"}},{"type":"text","data":{"text":"title：Prinz Eugen  大破图\n"}},{"type":"text","data":{"text":"id：66569463\n"}},{"type":"text","data":{"text":"tags：#R-18 #アズールレーン #碧蓝航线 #プリンツ・オイゲン(アズールレーン) #欧根亲王(碧蓝航线) #Azur Lane #PrinzEugen #乳ぼくろ #胸痣 #横乳 #侧乳 #咥え手袋 #holding glove in mouth #艤装アレンジ #rigging arrangement #大破 #heavy damage"}}]}, retcode: 100
                            at _Internal._get (/koishi/node_modules/@satorijs/adapter-onebot/lib/index.js:111:11)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async _Internal.<computed> [as sendGroupMsg] (/koishi/node_modules/@satorijs/adapter-onebot/lib/index.js:142:20)
                            at async OneBotMessenger.flush (/koishi/node_modules/@satorijs/adapter-onebot/lib/index.js:704:159)
                            at async OneBotMessenger.send (/koishi/node_modules/@satorijs/core/lib/index.cjs:372:5)
2023-03-27 17:08:20 [E] pixiv 消息发送失败，账号可能被风控，失败图片url：https://i.pixiv.re/img-original/img/2018/01/01/00/15/32/66569463_p1.png
2023-03-27 17:09:32 [W] gocqhttp 转换消息 [CQ:image,file=https://i.pixiv.re/img-original/img/2022/08/30/00/00/50/100857231_p0.jpg] 到MiraiGo Element时出现错误: context deadline exceeded (Client.Timeout or context cancellation while reading body).

**Comment by xmbhjQAQ** [comment]
能否将图片和信息整合以聊天记录的形式发出来呢..
这样可能可以规避风控.
（novelai插件就是这么干的）
感谢

**Comment by Rinkuto** [comment]
确实可以，那我还可以加一个发多少图片的选项（？）

**Comment by winteraven217** [comment]
今天刚装上插件，小群试了几次都是以聊天记录的形式正常发出来的，但是正式拉到大群里使用的时候突然就变成“账号可能被风控”了_(:з)∠)_，然后小群也发不出了

**Comment by winteraven217** [comment]
Error: Error with request send_group_forward_msg, args: {"group_id":"419601564","messages":[{"type":"node","data":{"name":"表妹长大了不可口了","uin":"279516097","content":[{"type":"image","data":{"file":"https://i.pixiv.re/img-original/img/2022/07/11/20/02/11/99657322_p0.png"}},{"type":"text","data":{"text":"\ntitle：★\n"}},{"type":"text","data":{"text":"id：99657322\n"}},{"type":"text","data":{"text":"tags：#R-18 #原神 #Genshin Impact #夜蘭 #Yelan #バニーガール #兔女郎 #おっぱい #欧派 #すじ #骆驼趾 #ふともも #大腿 #巨乳 #large breasts #爆乳 #huge breasts"}}],"time":"1681322718"}}]}, retcode: 100
                            at _Internal._get (C:\Users\RWS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\adapter-onebot\lib\index.js:111:11)
                            at processTicksAndRejections (node:internal/process/task_queues:96:5)
                            at async _Internal.<computed> [as sendGroupForwardMsg] (C:\Users\RWS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\adapter-onebot\lib\index.js:142:20)
                            at async OneBotMessenger.forward (C:\Users\RWS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\adapter-onebot\lib\index.js:665:45)
                            at async OneBotMessenger.visit (C:\Users\RWS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\adapter-onebot\lib\index.js:812:9)
                            at async OneBotMessenger.render (C:\Users\RWS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:359:7)
                            at async OneBotMessenger.visit (C:\Users\RWS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\adapter-onebot\lib\index.js:821:7)
                            at async OneBotMessenger.render (C:\Users\RWS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:359:7)
                            at async OneBotMessenger.send (C:\Users\RWS\AppData\Roaming\Koishi\Desktop\data\instances\default\node_modules\@satorijs\core\lib\index.cjs:371:5)

**Comment by CCXXXI** [comment]
现在合并转发已经不比直接发更稳定了，反而更容易发不出去

加个发送方式的选项，或者换回原来的方式吧

### 参考

- https://github.com/Mrs4s/go-cqhttp/issues/2167
- https://github.com/Mrs4s/go-cqhttp/issues/2087
- https://github.com/Mrs4s/go-cqhttp/issues/2023
